<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="SVFL-XAADQAF-13" name="HFIC.Testcases.com.Enrollment_360" tests="24" failures="2" timestamp="07 Apr 2021 19:27:46 GMT" time="213.424" errors="0">
  <testcase name="HFIC_InValid_GRPnumSearch" time="6.656" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="HFIC_InValid_GRPnameSearch" time="6.089" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="HFIC_InValid_EffdateSearch" time="6.119" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="HFIC_InValid_taxSearch" time="6.022" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="invalid_Group_Healthpass_Group_ID_Search" time="7.958" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="HFIC_Valid_GRPSearch" time="9.397" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="HP_invalid_Group_Eff_Search" time="8.035" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="HP_Group_Search" time="9.076" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="InvalidHFICMember360" time="7.398" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="InvalidHFICMembereffectdate" time="7.416" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="ValidHFIC_MemberSearch" time="10.042" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="InvalidHPMembereffectdate" time="7.461" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="InvalidHPMember360" time="7.385" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="Valid_HP_MemberSearch" time="9.933" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="OMI_Invalid_Fname" time="9.790" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="OMI_Invalid_Lname" time="9.875" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="OMI_Invalid_DOB" time="9.862" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="OMI_Invalid_SSN" time="9.946" classname="HFIC.Testcases.com.Enrollment_360">
    <failure type="java.lang.AssertionError" message="Testpass expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Testpass expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at HFIC.Pages.com.Enrollment360.merror(Enrollment360.java:83)
at HFIC.Testcases.com.Enrollment_360.OMI_Invalid_SSN(Enrollment_360.java:288)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- OMI_Invalid_SSN -->
  <testcase name="OMI_valid_MemberSearch" time="12.448" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="OMI_Invalid_HP_Fname" time="10.339" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="OMI_Invalid_HP_Lname" time="9.917" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="OMI_Invalid_HP_DOB" time="9.958" classname="HFIC.Testcases.com.Enrollment_360"/>
  <testcase name="OMI_Invalid_HP_SSN" time="9.852" classname="HFIC.Testcases.com.Enrollment_360">
    <failure type="java.lang.AssertionError" message="Testpass expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Testpass expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at HFIC.Pages.com.Enrollment360.merror(Enrollment360.java:83)
at HFIC.Testcases.com.Enrollment_360.OMI_Invalid_HP_SSN(Enrollment_360.java:366)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- OMI_Invalid_HP_SSN -->
  <testcase name="OMI_valid_HP_MemSearch" time="12.450" classname="HFIC.Testcases.com.Enrollment_360"/>
</testsuite> <!-- HFIC.Testcases.com.Enrollment_360 -->
